title = "Xiami and Last.fm Example"

[lastfm]
  domain = "http://ws.audioscrobbler.com"

  [lastfm.auth]
    api_key = "cf83895a868651092661968da89596ce"
    shared_secret = "55e7379e6dbc6c4ea499aedd352c45d0 "
    sk = ""
    token = ""
    token_expired = 0

[xiami]
  domain = "http://www.xiami.com"
  spm = ""
  user_id = 0
  checked_at = 0

  [xiami.url]
    recent = "/space/charts-recent/u/"
    fav_song = "/space/lib-song/u/"
