title = "Xiami and Last.fm Example"

[lastfm]
  domain = "http://ws.audioscrobbler.com"

  [lastfm.auth]
    sk = ""
    token = ""
    token_expired = 0

[xiami]
  domain = "http://www.xiami.com"
  spm = ""
  user_id = 0
  checked_at = 0

  [xiami.url]
    recent = "/space/charts-recent/u/"
    fav_song = "/space/lib-song/u/"
